### PR TITLE
Set Game no longer works, API changed.

### PR DESCRIPTION
**Pull request by ohlookitsderpy**

### CODE REVIEW

**Comment by ohlookitsderpy** [comment]
accept this :^)

**Comment by austinhuang0131** [comment]
But this is working tho

**Comment by ohlookitsderpy** [comment]
:eyes:

**Comment by austinhuang0131** [comment]
i mean you can also use `client.user.setPresence()`

**Comment by ohlookitsderpy** [comment]
i've tried ``setGame()`` and it doesn't work

**Comment by DafsCode** [comment]
smh discord. Cheers lad

**Pull request merged**
